### ISSUE TITLE
linking error on Mac OS (Undefined symbols for architecture x86_64)

### ISSUE THREAD

**Issue by jitongc** [LabSound/LabSoundDemo#1]
Hi, 
I was trying to run this demo on Mac OS Big Sur. I was not able build due to linking error.

scripts:
```
git clone https://github.com/LabSound/LabSoundDemo --recursive
cmake -DCMAKE_INSTALL_PREFIX="./install" ..
cmake --build . --target install --config Release
```

[ 51%] Built target libopus
[ 61%] Built target libwavpack
[ 66%] Built target libnyquist
[ 96%] Built target LabSound
[ 97%] Linking CXX executable LabSoundDemo
Undefined symbols for architecture x86_64:
  "_AudioDeviceCreateIOProcID", referenced from:
      RtApiCore::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) in LabSound(RtAudio.cpp.o)
  "_AudioDeviceDestroyIOProcID", referenced from:
      RtApiCore::closeStream() in LabSound(RtAudio.cpp.o)
  "_AudioDeviceStart", referenced from:
      RtApiCore::startStream() in LabSound(RtAudio.cpp.o)
  "_AudioDeviceStop", referenced from:
      RtApiCore::closeStream() in LabSound(RtAudio.cpp.o)
      RtApiCore::stopStream() in LabSound(RtAudio.cpp.o)
  "_AudioObjectAddPropertyListener", referenced from:
      RtApiCore::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) in LabSound(RtAudio.cpp.o)
  "_AudioObjectGetPropertyData", referenced from:
      RtApiCore::getDefaultInputDevice() in LabSound(RtAudio.cpp.o)
      RtApiCore::getDefaultOutputDevice() in LabSound(RtAudio.cpp.o)
      RtApiCore::getDeviceInfo(unsigned int) in LabSound(RtAudio.cpp.o)
      RtApiCore::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) in LabSound(RtAudio.cpp.o)
      rateListener(unsigned int, unsigned int, AudioObjectPropertyAddress const*, void*) in LabSound(RtAudio.cpp.o)
  "_AudioObjectGetPropertyDataSize", referenced from:
      RtApiCore::getDeviceCount() in LabSound(RtAudio.cpp.o)
      RtApiCore::getDeviceInfo(unsigned int) in LabSound(RtAudio.cpp.o)
      RtApiCore::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) in LabSound(RtAudio.cpp.o)
  "_AudioObjectHasProperty", referenced from:
      RtApiCore::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) in LabSound(RtAudio.cpp.o)
  "_AudioObjectRemovePropertyListener", referenced from:
      RtApiCore::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) in LabSound(RtAudio.cpp.o)
      RtApiCore::closeStream() in LabSound(RtAudio.cpp.o)
  "_AudioObjectSetPropertyData", referenced from:
      RtAudio::openRtApi(RtAudio::Api) in LabSound(RtAudio.cpp.o)
      RtApiCore::RtApiCore() in LabSound(RtAudio.cpp.o)
      RtApiCore::RtApiCore() in LabSound(RtAudio.cpp.o)
      RtApiCore::probeDeviceOpen(unsigned int, RtApi::StreamMode, unsigned int, unsigned int, unsigned int, unsigned long, unsigned int*, RtAudio::StreamOptions*) in LabSound(RtAudio.cpp.o)
  "_CFRelease", referenced from:
      RtApiCore::getDeviceInfo(unsigned int) in LabSound(RtAudio.cpp.o)
  "_CFStringGetCString", referenced from:
      RtApiCore::getDeviceInfo(unsigned int) in LabSound(RtAudio.cpp.o)
  "_CFStringGetLength", referenced from:
      RtApiCore::getDeviceInfo(unsigned int) in LabSound(RtAudio.cpp.o)
  "_CFStringGetSystemEncoding", referenced from:
      RtApiCore::getDeviceInfo(unsigned int) in LabSound(RtAudio.cpp.o)
  "_vDSP_create_fftsetup", referenced from:
      lab::FFTFrame::FFTFrame(int) in LabSound(FFTFrameAppleAcclerate.cpp.o)
      lab::FFTFrame::fftSetupForSize(int) in LabSound(FFTFrameAppleAcclerate.cpp.o)
  "_vDSP_ctoz", referenced from:
      lab::FFTFrame::computeForwardFFT(float const*) in LabSound(FFTFrameAppleAcclerate.cpp.o)
  "_vDSP_destroy_fftsetup", referenced from:
      lab::FFTFrame::cleanup() in LabSound(FFTFrameAppleAcclerate.cpp.o)
  "_vDSP_fft_zrip", referenced from:
      lab::FFTFrame::computeForwardFFT(float const*) in LabSound(FFTFrameAppleAcclerate.cpp.o)
      lab::FFTFrame::computeInverseFFT(float*) in LabSound(FFTFrameAppleAcclerate.cpp.o)
  "_vDSP_maxmgv", referenced from:
      lab::VectorMath::vmaxmgv(float const*, int, float*, int) in LabSound(VectorMath.cpp.o)
  "_vDSP_svesq", referenced from:
      lab::VectorMath::vsvesq(float const*, int, float*, int) in LabSound(VectorMath.cpp.o)
  "_vDSP_vadd", referenced from:
      lab::VectorMath::vadd(float const*, int, float const*, int, float*, int, int) in LabSound(VectorMath.cpp.o)
  "_vDSP_vclip", referenced from:
      lab::VectorMath::vclip(float const*, int, float const*, float const*, float*, int, int) in LabSound(VectorMath.cpp.o)
  "_vDSP_vmul", referenced from:
      lab::VectorMath::vmul(float const*, int, float const*, int, float*, int, int) in LabSound(VectorMath.cpp.o)
  "_vDSP_vsma", referenced from:
      lab::VectorMath::vsma(float const*, int, float const*, float*, int, int) in LabSound(VectorMath.cpp.o)
  "_vDSP_vsmul", referenced from:
      lab::VectorMath::vsmul(float const*, int, float const*, float*, int, int) in LabSound(VectorMath.cpp.o)
      lab::FFTFrame::computeInverseFFT(float*) in LabSound(FFTFrameAppleAcclerate.cpp.o)
  "_vDSP_ztoc", referenced from:
      lab::FFTFrame::computeInverseFFT(float*) in LabSound(FFTFrameAppleAcclerate.cpp.o)
  "_vDSP_zvmul", referenced from:
      lab::VectorMath::zvmul(float const*, float const*, float const*, float const*, float*, float*, int) in LabSound(VectorMath.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [LabSoundDemo] Error 1
make[1]: *** [CMakeFiles/LabSoundDemo.dir/all] Error 2
make: *** [all] Error 2

**Comment by meshula** [comment]
Hi, please pull now, it should work :) LMK how it goes. Fixed by: https://github.com/LabSound/LabSoundDemo/commit/272d676dd30066c68026207f8e3245aae0ddb655

**Comment by jitongc** [comment]
Works for me now, thanks!

**Comment by meshula** [comment]
Awesome, thank you for confirming!
